version: "3.9"

services:
  frontend:
    container_name: ecommerce-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: ./frontend/.env
    depends_on:
      - db
      - backend
  backend:
    container_name: ecommerce-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    env_file: ./backend/.env
    depends_on:
      - db
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pfweb
    volumes:
      - ./backend/database/create.sql:/docker-entrypoint-initdb.d/create.sql
